name: Go CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_dockerize:
    name: 🔨 Build & 🐳 Dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build Go Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o main
